### ISSUE TITLE
[stub] GS level advisor for new applicants

### ISSUE THREAD

**Issue by fureigh** [18F/joining-18f#129]
This is a stub for building a tool to help people find out which level they fit best. Why? To help applicants navigate what's often an unfamiliar process, and to in so doing mitigate some of the documented tendencies toward overestimation and underestimation of qualification (in the non-technical sense) that could otherwise lead to or perpetuate troubling pay discrepancies.

Expanding on #76, which delivered a minimum viable version of this, a text-based table.

**Comment by jackiekazil** [comment]
:+1:

**Comment by coreycaitlin** [comment]
Because of our shift to including requirements in each position description, each will include specialized qualifications — that approach should mitigate this concern somewhat. See the [Government Pay Grades section](https://18f.gsa.gov/join/#government-pay-grades) in the Join 18F page for the existing general guidance and link to GS salary calculator.

Fully resolving this point of confusion would likely be a much more ambitious project, and is out of scope for 18F talent content.
