### ISSUE TITLE
update sick leave

### ISSUE THREAD

**Issue by jamiealbrecht** [18F/joining-18f#51]
We need to correct the language around sick leave advances for FMLA. It should say something like this: 

When serving under a limited appointment employees can only be advanced sick leave up the total amount which would be earned during the term of that appointment. For our staff it would be what can be accrued in 2 years or less. 

It depends, obviously, on when they take the sick leave and how much they would be able to accrue in that time.

Also, FMLA is only available to those who have been at GSA a year.

cc @kaitlin

**Comment by rdpiazza** [comment]
Since sick leave can be "repaid" by either sick leave or annual leave accrual, it's still not possible to be advanced more than the sick leave you'd accrue for the rest of a 2 year term?  Or is it just that that would need to be done as advanced annual leave (which I believe is capped at the balance of leave you could earn for the rest of the annual leave year)?

**Comment by jamiealbrecht** [comment]
I think that I understand your question. Hopefully this helps. :) 

You can be advanced sick leave per the 2 year term max but you can only be advanced annual leave per the leave year max.  you can use a combo of sick and annual leave for parental leave but you still run into the max issues - of course there is also donated leave which gives you more time.

**Comment by kaitlin** [comment]
Hmmm this is annoying since nothing in this: 

https://www.opm.gov/policy-data-oversight/pay-leave/leave-administration/fact-sheets/handbook-on-leave-and-workplace-flexibilities-for-childbirth-adoption-and-foster-care.pdf

Says anything about term appointees specifically. Also this page
https://www.opm.gov/policy-data-oversight/pay-leave/leave-administration/fact-sheets/advanced-sick-leave/
Says all "full time employees" can be advanced 240 hours. Is this a GSA or OPM reg that we're talking about?

**Comment by jamiealbrecht** [comment]
Not sure. This was the guidance that Cristina received from GSA HR when it comes to excepted service employees.

**Comment by jamiealbrecht** [comment]
we made changes to the leave section to reflect that you can only advance up to what you'd accrue during your tenure. closing this.

**Comment by fureigh** [comment]
Noting for anyone who's looking: those changes are in c6e99782dc984e875b04cef6258e0c2f180c09db.
