### ISSUE TITLE
Give prospective applicants a way to find out about new job openings

### ISSUE THREAD

**Issue by fureigh** [18F/joining-18f#57]
**User story:**
As a prospective applicant, I want to know when positions for which I'm eligible open up so I can apply for them.

As someone on the hiring team, I want as many prospective applicants as possible to know about relevant openings so I can receive applications from all interested applicants at the appropriate times (and so I don't miss out on great candidates simply because they weren't continually checking the website).

**Current behavior:**
18F is currently hiring for only a few specific positions at a time. When the next round of openings are made active, updates are posted to the website. If prospective applicants see them, they see them. There's no built-in way for them to automatically receive updates.

**Desired behavior:**
Prospective applicants can in some way sign up to receive notifications when new openings are posted (or, perhaps, when specific relevant openings are posted).

**Technical notes:**
The simplest way to accomplish this is likely to:
1. encourage prospective applicants to sign up for the 18F mailing list, and 
2. be sure to include job openings in the newsletter.

**Outstanding questions:**
- Who writes content for the newsletters?
- How realistic is it that the schedule of job openings will neatly align with the newsletter schedule? (What are each of those schedules?)

**Comment by fureigh** [comment]
@jamiealbrecht (or anyone else who sees this and knows the answers!), what are your thoughts on the questions above?

**Comment by pixelwake** [comment]
bump
#124 brings additional clarity to the roles at 18F.

Since we allow applicants to apply based on skill and their role choice is only in essay format, hopefully we don't have many that wouldn't apply at the time they first look at the application.

However, they may apply and select a role that we aren't really looking for and therefor won't likely be selected. So it would be great to be able to communicate to those applicants when there is a role that's open and they are a fit for. We can use a newsletter/mailing list but we will also capture great data during the application so we could potentially even tailor the message even further.

**Comment by fureigh** [comment]
Yeah, the "desired behavior" part above is the crux of it:

> Prospective applicants can in some way sign up to receive notifications when new openings are posted (or, perhaps, when specific relevant openings are posted).

Or, as you said,

> it would be great to be able to communicate to those applicants when there is a role that's open and that they are a fit for

What's the next step here?

**Comment by fureigh** [comment]
@melodykramer proposed another approach in #237: an RSS feed! Conveniently, as long as it's a format that applicants find usable, an RSS feed won't require ongoing maintenance (content updates, etc.). Let's continue with specifics in that ticket.

**Comment by fureigh** [comment]
Closed en route to #273/#274.
