### ISSUE TITLE
Suggest ways to protect PII when sending required documents

### ISSUE THREAD

**Issue by fureigh** [18F/joining-18f#73]
Later stages of the application process require applicants to submit documents that include especially sensitive information such as their Social Security Numbers, signatures, etc. Some applicants choose workarounds like sending password-protected ZIP files and calling with the phone number, but for a variety of reasons, others don't.

Let's suggest ways applicants can protect their data so 1) they know if they don't already know and 2) it's clear that these approaches are welcome.

**Comment by fureigh** [comment]
cc @brittag. Want to pair on or have a go at this?

**Comment by NoahKunin** [comment]
Just to be clear to any open source contributors or auditors who come across this issue (hi!) that we _do_ already protect this data. Files are transmitted over HTTPS and stored with a Google Apps for Government infrastructure and software layer, that confirms to an even higher security standard than a normal Google Apps for Business instance would provide. 

Those files can only be accessed via official Government personnel with a business need to access them, via 2-factor authentication. 

This issue is addressing even **further enhancements** we could make to our security and privacy posture, potentially through further file-based encryption, ephemeral keys, or other techniques. This would further ensure that even if a Government's user account within Google Apps or other platforms is compromised in the future, or if the underlying Google infrastructure is compromised or used inappropriately, the hacker or adversary or insider threat could not access the sensitive PII of the applicant.

**Comment by fureigh** [comment]
Noting that https://fugacious.18f.gov is a good option to include.

**Comment by coreycaitlin** [comment]
Sounds like this is a bit out of scope for the narrowed focus of the Join 18F page on 18f.gsa.gov. Closing this issue for now, though the conversation is certainly interesting!
